### ISSUE TITLE
Android 15 不适配， 没办法start client() : ConnectionError: Video stream is disconnected

### ISSUE THREAD

**Issue by Robinmarsx** [leng-yue/py-scrcpy-client#91]
用安卓15的机器跑py-scrcpy 没办法启动客户端，总是报错： 

    m.client.start()
  File "C:\Users\mengzh\AppData\Local\Programs\Python\Python38\lib\site-packages\scrcpy\core.py", line 200, in start
    self.__stream_loop()
  File "C:\Users\mengzh\AppData\Local\Programs\Python\Python38\lib\site-packages\scrcpy\core.py", line 253, in __stream_loop
    raise e
  File "C:\Users\mengzh\AppData\Local\Programs\Python\Python38\lib\site-packages\scrcpy\core.py", line 234, in __stream_loop
    raise ConnectionError("Video stream is disconnected")
ConnectionError: Video stream is disconnected

感觉是core.py 那部分有问题，但又不知道问题是什么，lengyue大佬能解决下吗

**Comment by young-cloud-creator** [comment]
Update:
用现在官方仓库的最新一次提交或者v0.5.0可以正常运行，但是连接设备后最好先sleep一小会儿（比如1秒），不然可能会因为还没获取到分辨率信息和其他原因导致无法应用操作。
```TOML
[project]
dependencies = [
    # "scrcpy-client @ git+https://github.com/leng-yue/py-scrcpy-client.git@ad57b15"
    "scrcpy-client @ git+https://github.com/leng-yue/py-scrcpy-client.git@v0.5.0"
]
```
```Python
scrcpy_agent = scrcpy.Client()
scrcpy_agent.start(daemon_threaded=True)
sleep(1) # 这里如果不sleep也不暂停直接运行的话会导致获取到的resolution是26674x13876
width, height = scrcpy_agent.resolution
print(f"Width: {width}, Height: {height}")
scrcpy_agent.control.touch(628, 1380, ACTION_DOWN, FingerID.CLICK_FINGER.value)
scrcpy_agent.control.touch(628, 1380, ACTION_UP, FingerID.CLICK_FINGER.value)
scrcpy_agent.stop()
```

---

Android 15用pip安装的最新版本0.4.7，运行时会遇到ConnectionError: Video stream is disconnected，scrcpy.Client(device=device).resolution是正确的屏幕分辨率；
用poetry配置依赖为Github仓库的最新一次提交（ad57b15）之后运行不会报错崩溃，但是scrcpy.Client(device=device).resolution不对，试了两个Android 15设备resolution都是26674x13876，同时尝试用control.touch操作设备也没有作用：
```TOML
[project]
dependencies = [
    "scrcpy-client @ git+https://github.com/leng-yue/py-scrcpy-client.git@ad57b15"
]
```

Update: 我尝试了https://github.com/leng-yue/py-scrcpy-client/pull/87#issue-2754591914 这个版本，可以正常控制Android 15的设备，虽然返回的屏幕分辨率信息依然是26674x13876，但至少能完成点击之类的操作了
```TOML
[project]
dependencies = [
    "scrcpy-client @ git+https://github.com/xuzheliang135/py-scrcpy-client.git@a70362f"
]
```

Update:
屏幕分辨率这个问题应该是因为连接设备后立即尝试获取分辨率导致的，如果等一下会儿再获取就是正常的，我这里Android 15上面https://github.com/leng-yue/py-scrcpy-client/pull/87#issue-275459191 是可用的🙇‍
```Python
scrcpy_agent = scrcpy.Client()
scrcpy_agent.start(daemon_threaded=True)
sleep(1) # 这里如果不sleep也不暂停直接运行的话会导致获取到的resolution是26674x13876
width, height = scrcpy_agent.resolution
print(f"Width: {width}, Height: {height}")
scrcpy_agent.stop()
```
